---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-watcher-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-watcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-watcher-role
subjects:
  - kind: ServiceAccount
    name: secret-watcher-sa
